# Generated by Django 5.1.2 on 2024-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(verbose_name='Senha')),
                ('birth', models.DateField(null=True, verbose_name='Data de nascimento')),
            ],
        ),
    ]
