# Generated by Django 5.1.2 on 2024-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('birth', models.DateField(null=True, verbose_name='Data de nascimento')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
